### ISSUE TITLE
Per grid breakpoints?

### ISSUE THREAD

**Issue by skarfacegc** [nervetattoo/themable-grid#3]
Is it possible to define breakpoints per instance of the grid rather than globally?

**Comment by nervetattoo** [comment]
You should be able to use the same definition on a single card as globally yes. Let me know if that doesn't quite work for you.

**Comment by sanderabbink** [comment]
I think what he wants to do, I have the same problem with nested grids.
The first grid I want to have 4 columns, the one inside I want 3 columns.

Is this possible?

**Comment by nervetattoo** [comment]
Ah, nested grids, that is not something I've thought about for my own needs. Will investigate it when I have the time.

**Comment by sanderabbink** [comment]
This works great now! Thanks!
